# action.yml
name: 'MOxUnit Action'
description: 'Run unittests for Matlab/Octave using MOxUnit'
inputs:
  test_directory:
    description: 'directory containing the MOxUnit test cases'
    required: true
    default: '.'
  src_directory:
    description: 'directory of the source code'
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test_directory }}
    - ${{ inputs.src_directory }}