# action.yml
name: 'MOxUnit Action'
description: 'Run unittests for Matlab/Octave using MOxUnit'
inputs:
  tests:
    description: 'directory containing the MOxUnit test cases'
  src:
    description: 'directory of the source code'
  log_file:
    description: 'store the output in file output'
  doc_tests:
    description: 'run documentation tests with MOdoc'
  with_coverage:
    description: 'set to true to record coverage using MOCov'
  cover_xml_file:
    description: 'store coverage XML output in file'
  cover_html_dir:
    description: 'store coverage HTML output in directory'
  cover_junit_xml_file:
    description: 'store test results in junit XML file'
  cover_json_file:
    description: 'store coverage report in json file for  processing by coveralls.io'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tests }}
    - ${{ inputs.src }}
    - ${{ inputs.log_file }}
    - ${{ inputs.doc_tests }}
    - ${{ inputs.with_coverage }}
    - ${{ inputs.cover_xml_file }}
    - ${{ inputs.cover_html_dir }}
    - ${{ inputs.cover_junit_xml_file }}
    - ${{ inputs.cover_json_file }}